[package]
name = "rust_vreath_core"
version = "0.0.0"
authors = ["Sora Suegami"]
edition = "2018"

[dependencies]
rand = {version = "0.6.5", features = ["nightly"]}
hex = "0.3.2"
secp256k1 = { version = "0.12.2"}
sha2 = { version = "0.8.0"}
